name: Auto-Merge Package Bundle PRs

on:
  pull_request:
    types: [opened]
    
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Only run this workflow for PRs created by the package bundle process
    if: contains(github.event.pull_request.title, 'package bundle') || contains(github.event.pull_request.body, 'package bundle')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Auto-approve PR
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve
          
      - name: Auto-merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --auto
